export {
  Alert,
  AlertTypes,
  Autocomplete,
  Backdrop,
  Button,
  ButtonGroup,
  ButtonWithIcon,
  ButtonGroupContainer,
  Checkbox,
  CheckboxLabelPositions,
  CircleDraggablePoints,
  Collapse,
  CommaSeparatedInput,
  createButtonWithIcon,
  iconPositions,
  InlineEllipsis,
  CollapseGroup,
  ContextButton,
  ContextMenu,
  ContextOption,
  ContextOptionLink,
  ContextOptionReactLink,
  DatePicker,
  Description,
  DraggablePoints,
  Dropdown,
  DropdownButton,
  DropdownOption,
  DropdownOptionLink,
  DynamicPopover,
  EditableLabel,
  ErrorMessage,
  Fieldset,
  FileInput,
  FilterList,
  FilterPanel,
  FilterPanelCollapse,
  FilterLabel,
  FilterPopover,
  IconButton,
  Input,
  InputFieldWithPopover,
  IntegerInputWithControls,
  Label,
  List,
  ListItem,
  LoadConstraintPanel,
  LoadSpecificationChart,
  Modal,
  ModalWithBackdrop,
  ModalGroup,
  Multiselect,
  MultilineEllipsis,
  MultilineEllipsisPopover,
  Pagination,
  Panel,
  PanelHeader,
  PanelMenu,
  PanelUtils,
  PieChart,
  Placeholder,
  PlayerButton,
  PlayerDuration,
  Popover,
  POPOVER_OPEN_TRIGGER,
  POPOVER_PLACEMENTS,
  POPOVER_TYPES,
  Progress,
  ProgressStatus,
  ProgressStatusStage,
  SchedulePicker,
  SchedulePickerGroup,
  SearchDropdown,
  SelectableOptionsList,
  Table,
  TableBodyWithExpandRows,
  TableCell,
  TableCellWithTextEllipsis,
  TableHeadCell,
  TableHeadRow,
  TableHeadRowForExpandRows,
  TableRowWithExpandContent,
  TableWithPagination,
  TABLE_SORT_ORDER,
  Tabs,
  TestQueueDropdownOptionLabel,
  TextArea,
  TextPlaceholder,
  Tile,
  TilesList,
  Timeline,
  ToggleButton,
  ToggleButtonWithPopover,
  TOGGLE_BUTTON_SIZES,
  VolumeHandler,
  VolumeLabel,
  VERSION,
  withBackdrop,
  withPagination,
  withCharactersLimit
}

export namespace dataTestElementPropUtils {
  type DTE = (
    propsOrStaticValue: string | { [key: string]: any },
    process?: (dataTestElementPropValue: string) => string
  ) => object;

  export const getDataTestElementProps: DTE;
  export const DTE: DTE;
};

export const DTE: dataTestElementPropUtils.DTE;
